# Stage 1: Build React app
FROM node:22-alpine as builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Nhận biến môi trường lúc build
ARG VITE_USER_API
ARG VITE_MESSAGE_API
ARG VITE_STORAGE_API
ARG VITE_SERVER_API
ARG VITE_VOICE_API

ENV VITE_USER_API=$VITE_USER_API \
    VITE_MESSAGE_API=$VITE_MESSAGE_API \
    VITE_STORAGE_API=$VITE_STORAGE_API \
    VITE_SERVER_API=$VITE_SERVER_API \
    VITE_VOICE_API=$VITE_VOICE_API

RUN npm run build

# Stage 2: Serve bằng nginx
FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

# Cấu hình mặc định đã ok rồi
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
