apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-chat-message-service
  labels:
    app: echo-chat-message-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-chat-message-service
  template:
    metadata:
      labels:
        app: echo-chat-message-service
    spec:
      containers:
        - name: echo-chat-message-service
          image: huukhanh0653/echo-chat-message-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: MONGO_URI
              value: mongodb://35.225.51.17:27117/message_service?directConnection=true
            - name: REDIS_USERNAME
              value: default
            - name: REDIS_PASSWORD
              value: Pe5yLucM7SNhDOwyg6sjvc9Vpa3kg5km
            - name: REDIS_HOST
              value: redis-11124.fcrce171.ap-south-1-1.ec2.redns.redis-cloud.com
            - name: REDIS_PORT
              value: "11124"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: echo-chat-message-service
spec:
  selector:
    app: echo-chat-message-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
