apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: huukhanh0653/echo-chat-notification-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: REDIS_USERNAME
              value: default
            - name: REDIS_PASSWORD
              value: Pe5yLucM7SNhDOwyg6sjvc9Vpa3kg5km
            - name: REDIS_HOST
              value: redis-11124.fcrce171.ap-south-1-1.ec2.redns.redis-cloud.com
            - name: REDIS_PORT
              value: "11124"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "localhost:30092"
          resources:
            requests:
              cpu: "500m" 
              memory: "512Mi" 
            limits:
              cpu: "1000m" 
              memory: "1Gi" 
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: NodePort # Exposes the service internally within the cluster
