apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-chat-user-service
  labels:
    app: echo-chat-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-chat-user-service
  template:
    metadata:
      labels:
        app: echo-chat-user-service
    spec:
      containers:
        - name: echo-chat-user-service
          image: huukhanh0653/echo-chat-user-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: FIREBASE_SERVICE_ACCOUNT_KEY
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: echo-chat-user-service
spec:
  selector:
    app: echo-chat-user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
