services:
  backend:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Khanh076942542"
      TZ: "Asia/Ho_Chi_Minh"
      LC_ALL: "vi_VN.UTF-8"
      LANG: "vi_VN.UTF-8"
      COLLATION: "Vietnamese_CI_AS"
    ports:
      - "1433:1433"
    volumes:
      - advanced_db:/var/opt/mssql/data
volumes:
  advanced_db:
