Create or ALTER PROCEDURE SP_QUERY_PAGE
    @QUERY NVARCHAR(MAX),
    @PAGE INT = 1,
    @PAGESIZE INT = 25
AS BEGIN
    DECLARE @sql NVARCHAR(MAX);

    SET @sql = @QUERY + '
ORDER BY (SELECT NULL) OFFSET ' + CAST(@PAGESIZE * (@page - 1) AS VARCHAR) + ' ROWS FETCH NEXT ' + CAST(@PAGESIZE AS VARCHAR) + ' ROWS ONLY';
    EXEC sp_executesql @sql;
END; 
GO