version: '3.9'

services:
  redis-0:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7000:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.2

  redis-1:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.3

  redis-2:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.4

  redis-3:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7003:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.5

  redis-4:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7004:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.6

  redis-5:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7005:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 172.28.0.7

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
