apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-chat-message-service
  labels:
    app: echo-chat-message-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-chat-message-service
  template:
    metadata:
      labels:
        app: echo-chat-message-service
    spec:
      containers:
      - name: echo-chat-message-service
        image: huukhanh0653/message:v1.0
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_URL
          value: postgresql://postgres.halunphayrvdnvtcshoh:_3guQc4jik-zmWs@aws-0-us-west-1.pooler.supabase.com:6543/postgres
        - name: MONGO_URI
          value: mongodb+srv://vietlinhg4:5S88GUHWwbz8AHY@cluster0.ewhqtdg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
        - name: REDIS_USERNAME
          value: redis://redis-0.redis-headless.default.svc.cluster.local:6379 
---
apiVersion: v1
kind: Service
metadata:
  name: echo-chat-message-service
spec:
  selector:
    app: echo-chat-message-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP