apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-chat-message-service
  labels:
    app: echo-chat-message-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-chat-message-service
  template:
    metadata:
      labels:
        app: echo-chat-message-service
    spec:
      containers:
<<<<<<< HEAD:Kubenetes/echo-chat-message-service-deployment.yaml
        - name: echo-chat-message-service
          image: huukhanh0653/echo-chat-message-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: MONGO_URI
              value: mongodb+srv://vietlinhg4:5S88GUHWwbz8AHY@cluster0.ewhqtdg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
            - name: REDIS_USERNAME
              value: default
            - name: REDIS_PASSWORD
              value: cEjGBZrJH5FXXbyr1dzKabIHi4MQuWz8
            - name: REDIS_HOST
              value: redis-11588.c334.asia-southeast2-1.gce.redns.redis-cloud.com
            - name: REDIS_PORT
              value: "11588"
=======
      - name: echo-chat-message-service
        image: huukhanh0653/echo-chat-message-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: MONGO_URI
          value: mongodb://35.225.51.17:27117/message_service?directConnection=true
        - name: REDIS_USERNAME
          value: default
        - name: REDIS_PASSWORD
          value: cEjGBZrJH5FXXbyr1dzKabIHi4MQuWz8
        - name: REDIS_HOST
          value: redis-11588.c334.asia-southeast2-1.gce.redns.redis-cloud.com
        - name: REDIS_PORT
          value: "11588"
>>>>>>> e299f300904b16eb7dfa87187fc2fc20e53634d4:CI-CD/Kubenetes/message-service.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: echo-chat-message-service
spec:
  selector:
    app: echo-chat-message-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
<<<<<<< HEAD:Kubenetes/echo-chat-message-service-deployment.yaml
  type: LoadBalancer
=======
  type: LoadBalancer
>>>>>>> e299f300904b16eb7dfa87187fc2fc20e53634d4:CI-CD/Kubenetes/message-service.yaml
