// emojiData.js
export const emojiGroups = {
    // Nhóm "Mặt biểu cảm" -> key là "😀"
    "😀": [
      { unicode: "😀", name: ":grinning:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f600.png" },
      { unicode: "😁", name: ":grin:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f601.png" },
      { unicode: "😂", name: ":joy:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f602.png" },
      { unicode: "🤣", name: ":rofl:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f923.png" },
      { unicode: "😃", name: ":smiley:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f603.png" },
      { unicode: "😄", name: ":smile:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f604.png" },
      { unicode: "😅", name: ":sweatsmile:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f605.png" },
      { unicode: "😆", name: ":laughing:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f606.png" },
      { unicode: "😉", name: ":wink:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f609.png" },
      { unicode: "😊", name: ":blush:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f60a.png" },
      { unicode: "😋", name: ":yum:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f60b.png" },
      { unicode: "😎", name: ":sunglasses:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f60e.png" },
      { unicode: "😍", name: ":heart_eyes:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f60d.png" },
      { unicode: "😘", name: ":kiss:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f618.png" },
      { unicode: "🥰", name: ":smiling_face_with_3_hearts:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f970.png" },
      { unicode: "😗", name: ":kissing:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f617.png" },
      { unicode: "😙", name: ":kissing_face_with_smiling_eyes:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f619.png" },
      { unicode: "😚", name: ":kissing_closed_eyes:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f61a.png" },
      { unicode: "🙂", name: ":slight_smile:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f642.png" },
      { unicode: "🤗", name: ":hugging:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f917.png" },
      { unicode: "🤩", name: ":star_struck:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f929.png" },
      { unicode: "🤔", name: ":thinking:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f914.png" },
      { unicode: "🤨", name: ":raised_eyebrow:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f928.png" },
      { unicode: "😐", name: ":neutral_face:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f610.png" },
      { unicode: "😑", name: ":expressionless:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f611.png" },
      // Thêm 10 emoji nữa cho nhóm Mặt biểu cảm:
      { unicode: "😢", name: ":cry:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f622.png" },
      { unicode: "😭", name: ":sob:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f62d.png" },
      { unicode: "😩", name: ":weary:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f629.png" },
      { unicode: "😠", name: ":angry:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f620.png" },
      { unicode: "😡", name: ":pouting:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f621.png" },
      { unicode: "🤬", name: ":face_with_symbols_on_mouth:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f92c.png" },
      { unicode: "😤", name: ":triumph:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f624.png" },
      { unicode: "😪", name: ":sleepy:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f62a.png" },
      { unicode: "😴", name: ":sleeping:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f634.png" },
      { unicode: "🤤", name: ":drooling_face:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f924.png" }
    ],
    // Nhóm "Động vật" -> key là "🐶"
    "🐶": [
      { unicode: "🐶", name: ":dog:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f436.png" },
      { unicode: "🐱", name: ":cat:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f431.png" },
      { unicode: "🐭", name: ":mouse:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f42d.png" },
      { unicode: "🐹", name: ":hamster:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f439.png" },
      { unicode: "🐰", name: ":rabbit:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f430.png" },
      { unicode: "🦊", name: ":fox:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f98a.png" },
      { unicode: "🐻", name: ":bear:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f43b.png" },
      { unicode: "🐼", name: ":panda:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f43c.png" },
      { unicode: "🐨", name: ":koala:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f428.png" },
      { unicode: "🐯", name: ":tiger:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f42f.png" },
      { unicode: "🦁", name: ":lion:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f981.png" },
      { unicode: "🐮", name: ":cow:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f42e.png" },
      { unicode: "🐷", name: ":pig:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f437.png" },
      { unicode: "🐸", name: ":frog:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f438.png" },
      { unicode: "🐵", name: ":monkey:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f435.png" },
      { unicode: "🐔", name: ":chicken:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f414.png" },
      { unicode: "🐧", name: ":penguin:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f427.png" },
      { unicode: "🐦", name: ":bird:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f426.png" },
      { unicode: "🐤", name: ":chick:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f424.png" },
      { unicode: "🦆", name: ":duck:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f986.png" },
      { unicode: "🐴", name: ":horse:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f434.png" },
      { unicode: "🦄", name: ":unicorn:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f984.png" },
      { unicode: "🐝", name: ":bee:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f41d.png" },
      { unicode: "🐛", name: ":bug:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f41b.png" },
      { unicode: "🐌", name: ":snail:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f40c.png" },
      // Thêm 10 emoji nữa cho nhóm Động vật:
      { unicode: "🐢", name: ":turtle:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f422.png" },
      { unicode: "🐍", name: ":snake:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f40d.png" },
      { unicode: "🦎", name: ":lizard:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f98e.png" },
      { unicode: "🐙", name: ":octopus:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f419.png" },
      { unicode: "🦑", name: ":squid:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f991.png" },
      { unicode: "🦐", name: ":shrimp:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f990.png" },
      { unicode: "🦀", name: ":crab:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f980.png" },
      { unicode: "🐡", name: ":blowfish:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f421.png" },
      { unicode: "🐟", name: ":fish:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f41f.png" },
      { unicode: "🐬", name: ":dolphin:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f42c.png" }
    ],
    // Nhóm "Cử chỉ tay" -> key là "👍"
    "👍": [
      { unicode: "👍", name: ":thumbsup:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f44d.png" },
      { unicode: "👎", name: ":thumbsdown:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f44e.png" },
      { unicode: "👊", name: ":fist:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f44a.png" },
      { unicode: "✌️", name: ":v:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/270c.png" },
      { unicode: "🤞", name: ":crossed_fingers:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f91e.png" },
      { unicode: "🤟", name: ":love_you_gesture:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f91f.png" },
      { unicode: "👌", name: ":ok_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f44c.png" },
      { unicode: "✋", name: ":raised_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/270b.png" },
      { unicode: "👏", name: ":clap:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f44f.png" },
      { unicode: "🙌", name: ":raising_hands:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f64c.png" },
      { unicode: "🙏", name: ":pray:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f64f.png" },
      { unicode: "🤜", name: ":right_facing_fist:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f91b.png" },
      { unicode: "🤛", name: ":left_facing_fist:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f91c.png" },
      { unicode: "☝️", name: ":point_up:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/261d.png" },
      { unicode: "👆", name: ":point_up_2:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f446.png" },
      { unicode: "👇", name: ":point_down:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f447.png" },
      { unicode: "👈", name: ":point_left:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f448.png" },
      { unicode: "👉", name: ":point_right:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f449.png" },
      { unicode: "✊", name: ":raised_fist:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/270a.png" },
      { unicode: "🤚", name: ":raised_back_of_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f91a.png" },
      { unicode: "🖐️", name: ":hand_with_fingers_splayed:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f590.png" },
      { unicode: "👐", name: ":open_hands:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f450.png" },
      { unicode: "🤲", name: ":palms_up_together:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f932.png" },
      { unicode: "💪", name: ":flexed_biceps:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4aa.png" },
      // Thêm 10 emoji nữa cho nhóm Cử chỉ tay:
      { unicode: "🤘", name: ":sign_of_the_horns:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f918.png" },
      { unicode: "🤙", name: ":call_me_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f919.png" },
      { unicode: "🤏", name: ":pinching_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f90f.png" },
      { unicode: "👋", name: ":waving_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f44b.png" },
      { unicode: "🖖", name: ":vulcan_salute:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f596.png" },
      { unicode: "🤝", name: ":handshake:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f91d.png" },
      { unicode: "🙋", name: ":raising_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f64b.png" },
      { unicode: "🙆", name: ":ok:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f646.png" },
      { unicode: "🙅", name: ":no_good:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f645.png" },
      { unicode: "🙋‍♀️", name: ":woman_raising_hand:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f64b-200d-2640-fe0f.png" }
    ],
    // Nhóm "Các icon" -> key là "✅"
    "✅": [
      { unicode: "✅", name: ":check:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2705.png" },
      { unicode: "❌", name: ":cross:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/274c.png" },
      { unicode: "❤️", name: ":heart:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2764.png" },
      { unicode: "🔥", name: ":fire:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f525.png" },
      { unicode: "⭐", name: ":star:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2b50.png" },
      { unicode: "💯", name: ":100:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4af.png" },
      { unicode: "⚡", name: ":zap:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/26a1.png" },
      { unicode: "🎉", name: ":tada:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f389.png" },
      { unicode: "🔔", name: ":bell:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f514.png" },
      { unicode: "🔕", name: ":no_bell:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f515.png" },
      { unicode: "🔑", name: ":key:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f511.png" },
      { unicode: "🔒", name: ":lock:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f512.png" },
      { unicode: "🔓", name: ":unlock:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f513.png" },
      { unicode: "🚀", name: ":rocket:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f680.png" },
      { unicode: "💡", name: ":bulb:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4a1.png" },
      { unicode: "❗", name: ":exclamation:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2757.png" },
      { unicode: "❓", name: ":question:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/2753.png" },
      { unicode: "🔍", name: ":mag:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f50d.png" },
      { unicode: "📌", name: ":pushpin:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4cc.png" },
      { unicode: "📎", name: ":paperclip:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4ce.png" },
      { unicode: "✏️", name: ":pencil:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/270f.png" },
      { unicode: "📝", name: ":memo:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4dd.png" },
      { unicode: "📅", name: ":calendar:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4c5.png" },
      { unicode: "💬", name: ":speech_balloon:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f4ac.png" },
      { unicode: "⌛", name: ":hourglass:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/231b.png" },
      { unicode: "⏰", name: ":alarm_clock:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/23f0.png" },
      // Thêm 10 emoji nữa cho nhóm Các icon:
      { unicode: "🔀", name: ":shuffle:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f500.png" },
      { unicode: "🔁", name: ":repeat:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f501.png" },
      { unicode: "🔂", name: ":repeat_one:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f502.png" },
      { unicode: "⏩", name: ":fast_forward:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/23e9.png" },
      { unicode: "⏪", name: ":rewind:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/23ea.png" },
      { unicode: "↩️", name: ":leftwards_arrow_with_hook:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/21a9.png" },
      { unicode: "↪️", name: ":arrow_right_hook:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/21aa.png" },
      { unicode: "🛑", name: ":stop_sign:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f6d1.png" },
      { unicode: "🚦", name: ":traffic_light:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f6a5.png" },
      { unicode: "🚧", name: ":construction:", url: "https://cdnjs.cloudflare.com/ajax/libs/twemoji/14.0.2/72x72/1f6a7.png" }
    ]
  };
  