name: CI - Build Multi-Service Docker Images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB.DOCKER_PASSWORD }}

      - name: Build and Push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-User-Service
          file: ./Discord-User-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-user-service:latest

      - name: Build and Push Message Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-Message-Server
          file: ./Discord-Message-Server/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-message-service:latest

      - name: Build and Push Manage Server Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-Manage-Server 
          file: ./Discord-Manage-Server/Dockerfile
          push: true
          tags: huukhanh0653/order-service:latest

      - name: Build and Push GCS Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-GCS-Service
          file: ./Discord-GCS-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-gcs-service:latest
      
      - name: Build and Push Front-end Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-FE
          file: ./Discord-FE/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-front-end-service:latest
