name: Build Docker Images

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-User-Service
          file: ./Discord-User-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-user-service:latest

      - name: Build and Push Message Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-Message-Service
          file: ./Discord-Message-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-message-service:latest

      - name: Build and Push Server - Channel Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-Server-Channel-Service
          file: ./Discord-Server-Channel-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-manage-server:latest

      - name: Build and Push GCS Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-GCS-Service
          file: ./Discord-GCS-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-gcs-service:latest

      - name: Build and Push Front-end Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-FE
          file: ./Discord-FE/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-front-end-service:latest
          build-args: |
            VITE_USER_API=https://34.126.79.147.nip.io/api/user
            VITE_MESSAGE_API=https://34.126.79.147.nip.io/api/message
            VITE_STORAGE_API=https://34.126.79.147.nip.io/api/storage
            VITE_SERVER_API=https://34.126.79.147.nip.io/api/server-channel
            VITE_VOICE_API=https://34.126.79.147.nip.io/api/voice

      - name: Build and Push Notification Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-Notification-Service
          file: ./Discord-Notification-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-notification-service:latest

      - name: Build and Push Voice Chat Service
        uses: docker/build-push-action@v4
        with:
          context: ./Discord-VoiceChat-Service
          file: ./Discord-VoiceChat-Service/Dockerfile
          push: true
          tags: huukhanh0653/echo-chat-voicechat-service:latest
